using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bolinha : MonoBehaviour
{
    public Rigidbody2D ball;
    public float speed = 10f;
    public GameObject painel;

    void Start()
    {
        if (SystemInfo.supportsGyroscope)
        {
            Input.gyro.enabled = true;
        }
        else
        {
            Debug.LogError("ai fudeu neh pai");
        }
    }

    void Update()
    {
        if (Input.gyro.enabled)
        {
            Vector3 tilt = Input.gyro.gravity;

            Debug.Log("Girosc√≥pio - X: " + tilt.x + " | Y: " + tilt.y + " | Z: " + tilt.z);

            Vector2 movement = new Vector2(tilt.x, tilt.y);

            ball.AddForce(movement * speed);
        }
    }

    void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Final")) 
        {
            if (painel != null)
            {
                painel.SetActive(true);
            }
        }
    }
}
